name: exlipt_ai_test_task
description: "Eclipt AI test task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  build_runner: ^2.7.1 # Used for class generation
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_analytics: ^12.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_performance: ^0.11.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.2.4
  injectable: ^2.5.1
  injectable_generator: ^2.8.1 # Used for dependency injection for get_it
  intl: ^0.20.2
  intl_utils: ^2.8.11
  json_annotation: ^4.9.0 # Defines the annotations used by json_serializable
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  # images
  assets:
    - assets/images/

  fonts:

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
          style: normal
