name: exlipt_ai_test_task
description: "Eclipt AI test task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^6.0.2
  dartz: ^0.10.1
  email_validator: ^3.0.0
  equatable: ^2.0.7
  firebase_analytics: ^12.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  firebase_performance: ^0.11.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  freezed_annotation: ^3.1.0   # Needed at runtime for freezed models
  get_it: ^8.2.0
  go_router: ^16.2.4
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0      # Needed at runtime with json_serializable
  material_symbols_icons: ^4.2867.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.7.1          # Used for code generation
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0               # Code generator
  injectable_generator: ^2.8.1  # Generates injectable code for get_it
  json_serializable: ^6.11.0    # Code generator for JSON models
  intl_utils: ^2.8.11           # Generates localization files
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
          style: normal
