// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_mAOkjrfIJe9yTPxEXzY9z7C2kTGfCQ',
    appId: '1:557545971829:web:1f2b9be73aa77c5481d83c',
    messagingSenderId: '557545971829',
    projectId: 'eatery-7e66a',
    authDomain: 'eatery-7e66a.firebaseapp.com',
    storageBucket: 'eatery-7e66a.appspot.com',
    measurementId: 'G-68KGL0VVDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwmSTQJ1jshGg8yrndX-aV-xCKORCaVbc',
    appId: '1:557545971829:android:c4d9e688c14afef681d83c',
    messagingSenderId: '557545971829',
    projectId: 'eatery-7e66a',
    storageBucket: 'eatery-7e66a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoT1E4PWiOeDIe6v1PNbDugJK28jpWgpQ',
    appId: '1:557545971829:ios:4e2c1b44c0b97fdf81d83c',
    messagingSenderId: '557545971829',
    projectId: 'eatery-7e66a',
    storageBucket: 'eatery-7e66a.appspot.com',
    iosBundleId: 'com.example.exlipt_ai_test_task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoT1E4PWiOeDIe6v1PNbDugJK28jpWgpQ',
    appId: '1:557545971829:ios:2f6675bff40ef3b081d83c',
    messagingSenderId: '557545971829',
    projectId: 'eatery-7e66a',
    storageBucket: 'eatery-7e66a.appspot.com',
    iosBundleId: 'com.example.exlipt_ai_test_task.RunnerTests',
  );
}
